# Generated by Django 5.2 on 2025-05-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwors',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
