# Generated by Django 5.1.7 on 2025-04-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='new_field',
            field=models.CharField(default='default_value', max_length=200),
        ),
    ]
