# Generated by Django 5.1.3 on 2025-03-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
