# Generated by Django 5.2 on 2025-04-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0002_category_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
