# Generated by Django 5.2 on 2025-04-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0002_department_sale_employee'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['salary'], name='salary_idx'),
        ),
    ]
