# Generated by Django 5.1.3 on 2025-04-21 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0002_book_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='new_field',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='books',
        ),
        migrations.AddField(
            model_name='reader',
            name='books_read',
            field=models.ManyToManyField(related_name='readers', to='draft_app.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='draft_app.author'),
        ),
    ]
