# Generated by Django 5.1.3 on 2025-04-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0004_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-fiction'), ('fantasy', 'Fantasy'), ('sci-fi', 'Science Fiction'), ('mystery', 'Mystery'), ('biography', 'Biography'), ('history', 'History'), ('education', 'Education')], default='fiction', max_length=20),
        ),
    ]
